### ISSUE TITLE
Exceptions when loading the model

### ISSUE THREAD

**Issue by twmht** [ai-tor/DeepGTAV#6]
@ai-tor 

I installed keras and theano on windows 10.

But having exceptions when loading the model you give.

```
(deepDrive) C:\Users\GTA-01\VPilot>python drive.py model.json 8000 224 224
Using Theano backend.
Traceback (most recent call last):
  File "drive.py", line 55, in <module>
    model = model.getModel(model_path=args.model)
  File "C:\Users\GTA-01\VPilot\model.py", line 17, in getModel
    model = model_from_json(jfile.read())
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\models.py", line 197, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\utils\layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\models.py", line 996, in from_config
    layer = get_or_create_layer(first_layer)
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\models.py", line 980, in get_or_create_layer
    layer = layer_from_config(layer_data)
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\utils\layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\layers\core.py", line 497, in from_config
    function = marshal.loads(config['function'].encode('raw_unicode_escape'))
AttributeError: 'list' object has no attribute 'encode'
```

I am not sure if this is the keras issue.

**Comment by ai-tor** [comment]
Hi! Can we talk about it in VPilot repo? :)

**Comment by twmht** [comment]
oops. I am sorry.
