### ISSUE TITLE
Cut off JSON data from DeepGTAV

### ISSUE THREAD

**Issue by szpon** [ai-tor/DeepGTAV#70]
I tried to use dataset example from VPilot repo. Every time it was connecting to DeepGTAV and then JSONDecodeError popped out.

```
➜  VPilot git:(master) ✗ python3 dataset.py --host=192.168.2.35
Trying to connect to DeepGTAV
Successfully connected to DeepGTAV
Traceback (most recent call last):
  File "dataset.py", line 35, in <module>
    message = client.recvMessage()  
  File "/Users/marcinzadka/Desktop/DeepGTAV/VPilot/deepgtav/client.py", line 57, in recvMessage
    return self.targets.parse(frame, data.decode('utf-8'))
  File "/Users/marcinzadka/Desktop/DeepGTAV/VPilot/deepgtav/client.py", line 18, in parse
    dct = json.loads(jsonstr)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 44 (char 43)
```

I put breakpoint inside `recvMessage` and I found out that `data.decode('utf-8')` returns cut off JSON.

```
➜  VPilot git:(master) ✗ python3 dataset.py --host=192.168.2.35
Trying to connect to DeepGTAV
Successfully connected to DeepGTAV
> /Users/marcinzadka/Desktop/DeepGTAV/VPilot/deepgtav/client.py(58)recvMessage()
-> return self.targets.parse(frame, data.decode('utf-8'))
(Pdb) data.decode('utf-8')
'{"reward":-1.0,"throttle":'
```

I checked packets with Wireshark and clearly there's a packet with `{"reward":-1.0,"throttle":` data.

<img width="784" alt="zrzut ekranu 2017-09-01 o 14 58 29" src="https://user-images.githubusercontent.com/706471/29970774-314c92ce-8f26-11e7-9986-e29f31f6bccf.png">

I tried to pass `throttle=False` to Dataset and everything was fine, but throttle is an important thing to acquire.

Do you know what's the cause of this problem?
Thanks!

**Comment by ai-tor** [comment]
Hi @szpon,

This is a strange behavior, I wonder why DeepGTAV is sending cut off packets. Maybe rapidjson is getting confused somehow in your DeepGTAV computer. Can you tell me what are the specs of your Asrock machine and also OS and language settings?

Also, maybe you can try to run both DeepGTAV and VPilot in the same machine

**Comment by szpon** [comment]
Hi,
my computer specs:
CPU: i7 2600k
GPU: GTX 1060 6GB
RAM: 6GB
OS: Windows 7 Pro x64 Polish

I was connecting with VPilot on Macbook over ac WiFi but I also tried to run both DeepGTAV and VPilot on Windows PC and nothing changed.

I'm using xbox 360 controller to drive vehicles in GTA V, maybe this is somehow related to the cause.

Thanks!

**Comment by frmsvrt** [comment]
Same error here. But in my case i have to set steering to false:
`"steering":
Packet received 
Packet received 
Packet received 
Packet received 
Gen message: {"vehicles":[{"FUR":[7.55615234375,24.232421875,0.9258499145507813],"BLL":[4.70703125,19.48291015625,-0.5670700073242188],"speed":11.120205879211426,"heading":349.5805969238281,"classID":0},{"FUR":[4.81982421875,16.459228515625,1.3526153564453126],"BLL":[-0.23193359375,15.201171875,-0.650970458984375],"speed":2.4462201595306398,"heading":289.1987609863281,"classID":0}],"brake":0.0,"steering":

Error receiving message length: 10053`

**Comment by ai-tor** [comment]
I am looking into it, but it is difficult to reproduce in my end. What is your setup @frmsvrt ?

**Comment by szpon** [comment]
I modified `client.py` from VPilot to prevent it from crash if corrupted JSON comes from DeepGTAV. And I noticed that there is a problem with `throttle`, `brake` and `steering`. Throttle and brake are always `0.0` and steering have very high negative values.

```
{"reward":-1.0,"throttle":0.0,"brake":0.0,"steering":-3.092539512579276e22,"speed":10.31135368347168,"yawRate":33.240024011024477,"location":[308.101806640625,6564.765625,29.264324188232423],"time":12}
{"reward":-1.0,"throttle":0.0,"brake":0.0,"steering":-1.9960246925853196e23,"speed":10.98959732055664,"yawRate":-7.26051072451694,"location":[309.51031494140627,6565.111328125,29.22625732421875],"time":12}
[...]
{"reward":-1.0,"throttle":0.0,"brake":0.0,"steering":-690517943084271900.0,"speed":14.865571022033692,"yawRate":16.734028353327255,"location":[362.33380126953127,6561.55126953125,27.95114517211914],"time":12}
{"reward":-1.0,"throttle":0.0,"brake":0.0,"steering":-3465483158158611000.0,"speed":12.43241024017334,"yawRate":2.005162753746018,"location":[364.5746765136719,6561.490234375,27.907743453979493],"time":12}
{"reward":-1.0,"throttle":0.0,"brake":0.0,"steering":-2543375964452010000.0,"speed":9.915214538574219,"yawRate":-5.2948787578094269,"location":[366.41741943359377,6561.484375,27.872268676757814],"time":12}
{"reward":-1.0,"throttle":0.0,"brake":0.0,"steering":-930679850258736300.0,"speed":7.372552394866943,"yawRate":-5.615773851621298,"location":[367.83709716796877,6561.50830078125,27.847509384155275],"time":12}
```

**Comment by ai-tor** [comment]
Thanks @szpon!

You can make a Pull Request if you want to merge your changes with the master branch.

Regarding the values, it seems that the new GTAV version screwed up the memory offsets again and I will need to find them again. This is a somewhat difficult task, so it may take me two or three days to find them.

**Comment by ai-tor** [comment]
I found them already, will push to master in a few hours (need to attend personal issues now)

**Comment by szpon** [comment]
@ai-tor I created a pull request with simple JSON validation to prevent VPilot from crashing.
After your last change to memory offsets `throttle` and `brake` work fine for me, but I still have problem with `steering`. I have broken JSON just after connection and if I turn `steering` gets constant negative values.

There is how it looks when I connect and made quick left and right turns.
```
Trying to connect to DeepGTAV
Successfully connected to DeepGTAV
{"throttle":0.0,"brake":0.20000000298023225,"steering":
{"throttle":0.0,"brake":1.0,"steering":
{"throttle":0.0,"brake":1.0,"steering":
{"throttle":0.0,"brake":1.0,"steering":
{"throttle":0.0,"brake":1.0,"steering":
{"throttle":0.0,"brake":1.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.0,"brake":0.0,"steering":
{"throttle":0.717647135257721,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2575.20703125,3299.520751953125,13.23784065246582]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2575.03466796875,3300.510498046875,13.24307918548584]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.912841796875,3301.547607421875,13.249914169311524]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.861328125,3302.459716796875,13.255537033081055]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.847900390625,3303.379638671875,13.261261940002442]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.840087890625,3304.431640625,13.266983985900879]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.76123046875,3305.57421875,13.273677825927735]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.6181640625,3306.39208984375,13.279425621032715]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.358642578125,3307.36376953125,13.285881996154786]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2574.089111328125,3308.20556640625,13.291760444641114]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.76220703125,3309.24072265625,13.295818328857422]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.485595703125,3310.302978515625,13.300331115722657]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.291015625,3311.47119140625,13.307634353637696]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.226806640625,3312.558349609375,13.314162254333496]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.254150390625,3313.748779296875,13.319490432739258]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.319580078125,3314.980224609375,13.329658508300782]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283186078071594,"drivingMode":0,"location":[-2573.344970703125,3316.43701171875,13.341289520263672]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.284912109375,3317.535888671875,13.348976135253907]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2573.129150390625,3318.627685546875,13.356720924377442]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2572.863037109375,3319.712646484375,13.363762855529786]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2572.397705078125,3320.974365234375,13.368322372436524]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2571.823974609375,3322.251953125,13.37118911743164]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2571.23974609375,3323.548828125,13.373767852783204]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2570.698974609375,3324.925537109375,13.379342079162598]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2570.280517578125,3326.349609375,13.388507843017579]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2570.016845703125,3327.83740234375,13.397677421569825]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2569.9091796875,3329.129638671875,13.397443771362305]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2569.877197265625,3330.69384765625,13.390532493591309]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2569.85400390625,3332.299072265625,13.376651763916016]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2569.759033203125,3333.96044921875,13.36362075805664]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2569.4794921875,3335.8984375,13.349702835083008]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2569.061279296875,3337.584716796875,13.334892272949219]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2568.36962890625,3339.5087890625,13.318422317504883]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2567.76513671875,3340.937744140625,13.308555603027344]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2567.138671875,3342.392333984375,13.303361892700196]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283186078071594,"drivingMode":0,"location":[-2566.43408203125,3344.19580078125,13.298532485961914]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283184885978699,"drivingMode":0,"location":[-2565.853271484375,3346.06787109375,13.29287338256836]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2565.43701171875,3347.996826171875,13.279906272888184]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2565.204833984375,3349.990234375,13.263970375061036]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2565.116455078125,3352.0029296875,13.248160362243653]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2565.06005859375,3354.067138671875,13.230369567871094]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283184885978699,"drivingMode":0,"location":[-2564.94189453125,3356.1357421875,13.215800285339356]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2564.66845703125,3358.258056640625,13.203145027160645]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2564.203125,3360.3330078125,13.193524360656739]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2563.5400390625,3362.37109375,13.186017990112305]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2562.752685546875,3364.364501953125,13.17985725402832]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2561.937744140625,3366.337158203125,13.174742698669434]}
{"throttle":1.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2561.171875,3368.377197265625,13.168896675109864]}
{"throttle":0.9947713017463684,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2560.54736328125,3370.495849609375,13.161563873291016]}
{"throttle":0.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2560.091552734375,3372.625244140625,13.15296459197998]}
{"throttle":0.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2559.7763671875,3374.729736328125,13.142716407775879]}
{"throttle":0.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2559.57470703125,3376.7958984375,13.131577491760254]}
{"throttle":0.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2559.4599609375,3378.4990234375,13.122221946716309]}
{"throttle":0.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2559.37158203125,3380.15576171875,13.112914085388184]}
{"throttle":0.0,"brake":0.0,"steering":-0.6283185482025147,"drivingMode":0,"location":[-2559.30615234375,3381.534912109375,13.10490608215332]}
```

Thanks!

**Comment by ai-tor** [comment]
Thanks @szpon !
I've already merged it with the master branch. I will test this issue now and try to fix it.
