### ISSUE TITLE
can't capture data with GTAV 1.0.1290

### ISSUE THREAD

**Issue by IanKirwan** [ai-tor/DeepGTAV#86]
I have updated scripthookv to the latest and am able to control GTAV using DeepGTAV, just can't capture. 

```
Using TensorFlow backend.
Trying to connect to DeepGTAV
ERROR: Failed to connect to DeepGTAV
ERROR: Failed to send message. Reason: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
2017-12-24 19:13:25.994001: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2017-12-24 19:13:26.272740: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2017-12-24 19:13:26.273167: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)

Traceback (most recent call last):
  File "C:\Workspace\vpilot\tfdrive.py", line 68, in <module>
    message = client.recvMessage()  
  File "C:\Workspace\vpilot\deepgtav\client.py", line 49, in recvMessage
    frame = self._recvall()
  File "C:\Workspace\vpilot\deepgtav\client.py", line 66, in _recvall
    packet = self.s.recv(4 - len(data))
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
```
DeepGTAV.log reports:
```
Initializing Winsock...Initialized.
Socket created.
Bind done.
Listening...
Connection accepted.
Start received

Error sending frame length: 10053
```

BTW, I think this latest  update broke LauncherBypass

**Comment by IanKirwan** [comment]
Problem went away after restarting system.
